<h1 style="color:#38BDF8; text-align:center; font-weight:bold; border-bottom:3px solid #38BDF8;">Day 3 — Linear Algebra for ML</h1>
<h3 style="text-align:center; color:#BE185D;">Vectors, Matrices, the Dot Product &amp; Matrix Multiplication</h3>


<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">Table of Contents</h2>

<div style="border:1px solid #ccc; padding:15px 25px; border-radius:6px;">
<ol style="font-weight:bold; line-height:1.9;">
<li><a href="#section0">0. Setup — Importing NumPy</a></li>
<li><a href="#section1">1. Why Linear Algebra Is the Language of ML</a></li>
<li><a href="#section2">2. Vectors — One Sample's Features</a></li>
<li><a href="#section3">3. Matrices — A Full Dataset</a></li>
<li><a href="#section4">4. The Dot Product — How Models Predict</a></li>
<li><a href="#section5">5. Matrix Multiplication — Predicting for Every Sample at Once</a></li>
<li><a href="#section6">6. The Shape-Matching Rule &amp; Reading Shape-Mismatch Errors</a></li>
<li><a href="#section7">7. Common Mistakes to Avoid</a></li>
<li><a href="#section8">8. Quick Reference — Cheat Sheet</a></li>
<li><a href="#section9">9. Hands-On Lab — Vectors, Matrices &amp; Predictions</a></li>
<li><a href="#section10">10. Best Practices &amp; Reproducibility</a></li>
<li><a href="#section11">11. Summary — What I Learned Today</a></li>
</ol>
</div>


<a id="section0"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">0. Setup — Importing NumPy</h2>

<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> Today's entire toolbox is <b>NumPy</b> — the same library from Week 1. Linear algebra in Python is really just NumPy arrays, viewed through a new lens: as vectors and matrices instead of plain lists of numbers.
</div>


In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.6


<a id="section1"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">1. Why Linear Algebra Is the Language of ML</h2>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">1.1 Every dataset is secretly a matrix</h3>

Every dataset you will ever load into an ML model is, structurally, a <b>matrix</b>: rows are individual samples (customers, images, emails...), and columns are their features (age, income, pixel brightness...). Every model's internal parameters are themselves vectors or matrices, and the process of "training" a model is really just a long sequence of matrix operations, repeated over and over.

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">1.2 You don't need to prove it — you need to recognize it</h3>

You do not need to derive mathematical proofs to work in AI/ML. But you <b>do</b> need to recognize these objects on sight, and understand how they combine — because that is literally what a model is doing internally, every single time it makes a prediction.

<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b> Once you see it this way, Week 3's "linear regression" and "logistic regression" models will stop feeling like mysterious black boxes — they are just a dot product plus a bias, which you will fully understand by the end of today.
</div>


<a id="section2"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">2. Vectors — One Sample's Features</h2>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">2.1 What a vector is</h3>

A <b>vector</b> is simply an ordered list of numbers. In ML, a vector usually represents <b>one data sample's features</b> — one row of data. A customer described by <code>[age, income, tenure]</code> is a <b>3-dimensional vector</b>.


In [2]:
v = np.array([25, 50000, 3])   # a customer: age=25, income=50000, tenure=3 years

print("Vector:", v)
print("Shape :", v.shape)      # (3,) -- a 1D array with 3 elements
print("Number of dimensions (features):", v.shape[0])

Vector: [   25 50000     3]
Shape : (3,)
Number of dimensions (features): 3


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">2.2 Basic vector operations</h3>

Vectors support simple arithmetic, applied element-by-element — this should feel familiar from NumPy's vectorized operations in Week 1.


In [3]:
v1 = np.array([25, 50000, 3])
v2 = np.array([5, 2000, 1])

print("v1 + v2:", v1 + v2)      # adding corresponding elements
print("v1 - v2:", v1 - v2)
print("v1 * 2 :", v1 * 2)       # scaling every element by 2

v1 + v2: [   30 52000     4]
v1 - v2: [   20 48000     2]
v1 * 2 : [    50 100000      6]


<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> A vector's "length" in the linear-algebra sense (also called its <b>magnitude</b> or <b>norm</b>) tells you how big it is overall. NumPy computes it with <code>np.linalg.norm()</code>.
</div>

In [4]:
magnitude = np.linalg.norm(np.array([3, 4]))
print("Magnitude of [3, 4]:", magnitude)   # 5.0 -- the classic 3-4-5 right triangle!

Magnitude of [3, 4]: 5.0


<a id="section3"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">3. Matrices — A Full Dataset</h2>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">3.1 What a matrix is</h3>

A <b>matrix</b> is a 2D grid of numbers — a full dataset, where each <b>row</b> is a sample vector and each <b>column</b> is a feature. Its shape is <code>(rows, columns) = (samples, features)</code>.


In [5]:
X = np.array([[25, 50000, 3],
              [40, 80000, 10],
              [33, 62000, 5]])

print("Matrix X:\n", X)
print("Shape:", X.shape)    # (3, 3): 3 samples, 3 features

Matrix X:
 [[   25 50000     3]
 [   40 80000    10]
 [   33 62000     5]]
Shape: (3, 3)


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">3.2 Reading a matrix's shape</h3>

Reading matrix shapes correctly is one of the most important habits in ML code — most bugs come from a shape being different than you expected.


In [6]:
print(f"Number of samples (rows)   : {X.shape[0]}")
print(f"Number of features (columns): {X.shape[1]}")

# accessing one full row -- one customer's complete feature vector
print("\nFirst customer's data:", X[0])

# accessing one full column -- one feature, across all customers
print("Income column (all customers):", X[:, 1])

Number of samples (rows)   : 3
Number of features (columns): 3

First customer's data: [   25 50000     3]
Income column (all customers): [50000 80000 62000]


<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b> This is exactly the same indexing you learned for NumPy 2D arrays back in Week 1 — a matrix in linear algebra <i>is</i> a NumPy 2D array. Nothing new to learn syntax-wise, just a new way to interpret what the numbers mean.
</div>

<a id="section4"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">4. The Dot Product — How Models Predict</h2>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">4.1 What the dot product does</h3>

The <b>dot product</b> multiplies two vectors <b>element-by-element</b>, then <b>sums the results</b>, producing a single number. This is, without exaggeration, the single most important operation in all of machine learning.


In [7]:
features = np.array([25, 50000, 3])       # one customer's features
weights = np.array([0.1, 0.0002, 1.5])    # a model's learned "importance" for each feature

# The dot product, computed step by step:
elementwise_products = features * weights
print("Element-wise products:", elementwise_products)

manual_dot_product = elementwise_products.sum()
print("Sum (the dot product):", manual_dot_product)

# The same result, using NumPy's built-in function:
prediction = np.dot(features, weights)
print("np.dot() result      :", prediction)

Element-wise products: [ 2.5 10.   4.5]
Sum (the dot product): 17.0
np.dot() result      : 17.0


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">4.2 Why this matters: this is literally how a model predicts</h3>

<div style="border-left:5px solid #BE185D; background-color:#fff0f6; padding:10px 15px; margin:10px 0; border-radius:4px; color:#7a0d3d;">
<b>Important:</b> This is precisely how linear regression and logistic regression (coming in Week 3) compute their output:
<div style="text-align:center; margin-top:8px;"><code>prediction = dot(features, weights) + bias</code></div>
Understanding the dot product <i>is</i> understanding how these models actually predict — there is no hidden magic beyond this formula (plus, for logistic regression, one extra step to turn the number into a probability).
</div>


In [8]:
bias = 2.0   # a model's learned "baseline" adjustment

final_prediction = np.dot(features, weights) + bias
print("Final prediction (with bias):", final_prediction)

Final prediction (with bias): 19.0


<a id="section5"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">5. Matrix Multiplication — Predicting for Every Sample at Once</h2>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">5.1 From one prediction to many predictions</h3>

Computing one dot product gives one prediction, for one sample. But real datasets have <i>many</i> samples. <b>Matrix multiplication</b> applies the dot product across a whole matrix at once, letting a model predict for every sample in a dataset in a <b>single operation</b> — no loop required.


In [9]:
X = np.array([[25, 50000, 3],
              [40, 80000, 10]])     # (2, 3): 2 samples, 3 features

w = np.array([0.1, 0.0002, 1.5])    # (3,): 3 weights, one per feature

predictions = X @ w                 # matrix multiplication using the @ operator
print("Predictions for both samples:", predictions)

Predictions for both samples: [17. 35.]


<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> The <code>@</code> operator is Python's dedicated symbol for matrix multiplication (equivalent to <code>np.matmul(X, w)</code>). It is different from <code>*</code>, which multiplies element-by-element instead.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">5.2 The shape-matching rule</h3>

Matrix multiplication follows one strict rule: an <b>(m × n)</b> matrix times an <b>(n × p)</b> matrix gives an <b>(m × p)</b> matrix — <b>the inner dimensions must match</b>.


In [10]:
X = np.array([[25, 50000, 3], [40, 80000, 10]])   # shape (2, 3)
w = np.array([0.1, 0.0002, 1.5])                   # shape (3,)

print("X shape:", X.shape)   # (2, 3) -- 2 samples, 3 features
print("w shape:", w.shape)   # (3,)   -- 3 weights

predictions = X @ w
print("predictions shape:", predictions.shape)    # (2,) -- one prediction per sample, as expected

X shape: (2, 3)
w shape: (3,)
predictions shape: (2,)


<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b> A quick way to remember the rule: write the two shapes side by side, e.g. <code>(2, 3) @ (3,)</code>. The two "inner" numbers (both 3s here) must match — and they cancel out, leaving the "outer" numbers as the result shape: <code>(2,)</code>.
</div>

<a id="section6"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">6. The Shape-Matching Rule &amp; Reading Shape-Mismatch Errors</h2>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">6.1 Why shape mismatches are the #1 ML bug</h3>

Because matrix multiplication requires the inner dimensions to match, <b>shape mismatches are the single most common error in ML code</b>. Let's deliberately trigger one, so the error message becomes familiar instead of scary.


In [11]:
X = np.array([[25, 50000, 3], [40, 80000, 10]])   # shape (2, 3): 2 samples, 3 features
wrong_weights = np.array([0.1, 0.0002])            # shape (2,): only 2 weights, but we have 3 features!

try:
    predictions = X @ wrong_weights
except ValueError as e:
    print("ValueError caught:")
    print(e)

ValueError caught:
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


<div style="border-left:5px solid #BE185D; background-color:#fff0f6; padding:10px 15px; margin:10px 0; border-radius:4px; color:#7a0d3d;">
<b>Important — reading this error:</b> The message says the shapes <code>(2,3)</code> and <code>(2,)</code> are "not aligned," because the inner dimensions (<b>3</b> features vs. only <b>2</b> weights) do not match. In plain terms: <b>we gave the model a weight for only 2 out of the 3 features it expects.</b> The fix is always to make sure your weight vector has exactly one value per feature — here, that means <code>wrong_weights</code> needs a shape of <code>(3,)</code>, not <code>(2,)</code>.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">6.2 The fix</h3>


In [12]:
correct_weights = np.array([0.1, 0.0002, 1.5])   # now shape (3,) -- matches X's 3 features

predictions = X @ correct_weights
print("Predictions (fixed):", predictions)

Predictions (fixed): [17. 35.]


<a id="section7"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">7. Common Mistakes to Avoid</h2>

<div style="border-left:5px solid #BE185D; background-color:#fff0f6; padding:10px 15px; margin:10px 0; border-radius:4px; color:#7a0d3d;">
<b>Important:</b>
<ul>
<li><b>Confusing <code>*</code> and <code>@</code></b> — <code>*</code> multiplies element-by-element (requires the exact same shape), while <code>@</code> performs true matrix multiplication (requires matching <i>inner</i> dimensions). Using the wrong one either crashes or silently gives the wrong numbers.</li>
<li><b>Forgetting which axis is "samples" and which is "features"</b> — always double check <code>X.shape</code> before writing code; a transposed matrix will pass the shape-matching rule but produce a completely meaningless result.</li>
<li><b>Ignoring shape-mismatch errors instead of reading them</b> — the error message always tells you the exact shapes involved; use it to trace back which array has the wrong number of features or weights.</li>
<li><b>Forgetting the bias term</b> — a real linear model's prediction is <code>dot(features, weights) + bias</code>, not just the dot product alone.</li>
</ul>
</div>


<a id="section8"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">8. Quick Reference — Cheat Sheet</h2>

<div style="border:1px solid #ccc; border-radius:6px; overflow:hidden;">
<table style="width:100%; border-collapse:collapse;">
<tr style="background-color:#1f2933; color:#FACC15;">
<th style="padding:8px; text-align:left;">Concept</th>
<th style="padding:8px; text-align:left;">NumPy</th>
<th style="padding:8px; text-align:left;">Meaning</th>
</tr>
<tr><td style="padding:8px; border-top:1px solid #ccc;">Vector</td><td style="padding:8px; border-top:1px solid #ccc;"><code>np.array([1, 2, 3])</code></td><td style="padding:8px; border-top:1px solid #ccc;">One sample's features (1D array)</td></tr>
<tr><td style="padding:8px; border-top:1px solid #ccc;">Matrix</td><td style="padding:8px; border-top:1px solid #ccc;"><code>np.array([[...], [...]])</code></td><td style="padding:8px; border-top:1px solid #ccc;">A full dataset (2D array): (samples, features)</td></tr>
<tr><td style="padding:8px; border-top:1px solid #ccc;">Shape</td><td style="padding:8px; border-top:1px solid #ccc;"><code>X.shape</code></td><td style="padding:8px; border-top:1px solid #ccc;">(rows, columns) — always check this first</td></tr>
<tr><td style="padding:8px; border-top:1px solid #ccc;">Vector magnitude</td><td style="padding:8px; border-top:1px solid #ccc;"><code>np.linalg.norm(v)</code></td><td style="padding:8px; border-top:1px solid #ccc;">The "length" of a vector</td></tr>
<tr><td style="padding:8px; border-top:1px solid #ccc;">Dot product</td><td style="padding:8px; border-top:1px solid #ccc;"><code>np.dot(a, b)</code></td><td style="padding:8px; border-top:1px solid #ccc;">Element-wise multiply, then sum — a single prediction</td></tr>
<tr><td style="padding:8px; border-top:1px solid #ccc;">Matrix multiplication</td><td style="padding:8px; border-top:1px solid #ccc;"><code>X @ w</code></td><td style="padding:8px; border-top:1px solid #ccc;">Dot product applied across all rows at once</td></tr>
<tr><td style="padding:8px; border-top:1px solid #ccc;">Shape rule</td><td style="padding:8px; border-top:1px solid #ccc;">(m,n) @ (n,p) = (m,p)</td><td style="padding:8px; border-top:1px solid #ccc;">Inner dimensions (n) must match</td></tr>
<tr><td style="padding:8px; border-top:1px solid #ccc;">Linear model prediction</td><td style="padding:8px; border-top:1px solid #ccc;"><code>X @ w + bias</code></td><td style="padding:8px; border-top:1px solid #ccc;">What linear/logistic regression compute internally</td></tr>
</table>
</div>


<a id="section9"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">9. Hands-On Lab — Vectors, Matrices &amp; Predictions</h2>

<div style="border-left:5px solid #FACC15; background-color:#fffbea; padding:10px 15px; margin:10px 0; border-radius:4px; color:#78350f;">
<b>Goal:</b> Build a tiny "linear model" from scratch, exactly the way real models compute their predictions internally.
</div>


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">Step 1 — Represent three data samples as a (3 × features) NumPy matrix</h3>
<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> We'll represent three interns as rows, with three features each: <code>[hours_studied, previous_score, hours_slept]</code> — and try to predict their final exam score.
</div>

In [13]:
X = np.array([
    [10, 65, 7],    # intern 1: 10 study hours, 65 previous score, 7 hours slept
    [15, 70, 6],    # intern 2
    [5,  55, 8],    # intern 3
])

print("Data matrix X:\n", X)
print("Shape:", X.shape, "-> 3 samples, 3 features")

Data matrix X:
 [[10 65  7]
 [15 70  6]
 [ 5 55  8]]
Shape: (3, 3) -> 3 samples, 3 features


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">Step 2 — Compute the dot product of one sample vector with a weight vector by hand, then verify with np.dot</h3>

In [14]:
weights = np.array([2.0, 0.5, 1.0])   # made-up "importance" per feature: study hours matter most

sample_1 = X[0]   # the first intern's feature vector

# By hand:
by_hand = (sample_1[0]*weights[0]) + (sample_1[1]*weights[1]) + (sample_1[2]*weights[2])
print("Computed by hand:", by_hand)

# Verified with np.dot:
verified = np.dot(sample_1, weights)
print("Verified with np.dot:", verified)

print("Match:", by_hand == verified)

Computed by hand: 59.5
Verified with np.dot: 59.5
Match: True


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">Step 3 — Use matrix multiplication (@) to produce a prediction for all three samples at once</h3>

In [15]:
bias = 3.0

predicted_scores = X @ weights + bias
print("Predicted exam scores for all 3 interns:", predicted_scores)

for i, score in enumerate(predicted_scores, start=1):
    print(f"  Intern {i}: predicted score = {score:.1f}")

Predicted exam scores for all 3 interns: [62.5 74.  48.5]
  Intern 1: predicted score = 62.5
  Intern 2: predicted score = 74.0
  Intern 3: predicted score = 48.5


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">Step 4 — Deliberately create a shape-mismatch error, read the message, and explain why</h3>

In [16]:
# Deliberately using a weight vector with the wrong number of values (2 instead of 3)
broken_weights = np.array([2.0, 0.5])

try:
    X @ broken_weights
except ValueError as e:
    print("ValueError caught:")
    print(e)

ValueError caught:
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


<div style="border-left:5px solid #BE185D; background-color:#fff0f6; padding:10px 15px; margin:10px 0; border-radius:4px; color:#7a0d3d;">
<b>Important — explanation:</b> <code>X</code> has shape <code>(3, 3)</code> — 3 interns, each with 3 features. <code>broken_weights</code> has shape <code>(2,)</code> — only 2 weights. For matrix multiplication, the number of weights must exactly match the number of <i>features</i> (the inner dimension, here 3), because each weight is meant to be multiplied against one specific feature column. Since 3 ≠ 2, NumPy correctly refuses to guess what we meant, and raises a <code>ValueError</code> instead. The fix is simply to provide exactly one weight per feature — three weights for our three features, as we did successfully in Step 3.
</div>

<a id="section10"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">10. Best Practices &amp; Reproducibility</h2>

<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b> A professional checklist before running any matrix operation:
<ul>
<li>Print <code>.shape</code> for every array involved <b>before</b> multiplying — catching a mismatch before it crashes (or worse, silently succeeds with the wrong shapes) saves debugging time.</li>
<li>Know which axis represents <b>samples</b> and which represents <b>features</b> — write it in a comment if it isn't obvious.</li>
<li>Remember the shape rule as a simple phrase: <i>"the inner numbers must match, the outer numbers survive."</i></li>
<li>When something looks wrong, check the shapes first — the vast majority of ML bugs trace back to a shape mismatch somewhere upstream.</li>
</ul>
</div>


<a id="section11"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">11. Summary — What I Learned Today</h2>

<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b>
<ul>
<li>Every ML dataset is a <b>matrix</b>: rows are samples, columns are features — and every model's parameters are themselves vectors or matrices.</li>
<li>A <b>vector</b> is an ordered list of numbers, usually representing one sample's features; a <b>matrix</b> is a 2D grid of numbers, representing a whole dataset.</li>
<li>The <b>dot product</b> (<code>np.dot(a, b)</code>) multiplies two vectors element-by-element and sums the result — this is exactly how a linear model computes a single prediction: <code>dot(features, weights) + bias</code>.</li>
<li><b>Matrix multiplication</b> (<code>X @ w</code>) applies the dot product across an entire dataset at once, producing one prediction per sample in a single operation.</li>
<li>The <b>shape-matching rule</b>: an (m × n) matrix times an (n × p) matrix (or vector) gives an (m × p) result — the inner dimensions must always match.</li>
<li><b>Shape mismatches are the most common error in ML code</b> — always check <code>.shape</code> first, and read the error message carefully; it always tells you exactly which shapes didn't align.</li>
</ul>
</div>
