<h1 style="color:#38BDF8; text-align:center; font-weight:bold; border-bottom:3px solid #38BDF8;">Day 3 — NumPy</h1>


<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">Table of Contents</h2>

<div style="border:1px solid #ccc; padding:15px 25px; border-radius:6px;">
<ol style="font-weight:bold; line-height:1.9;">
<li><a href="#section0">0. Setup — Importing NumPy</a></li>
<li><a href="#section1">1. Why NumPy Exists — The Big Picture</a></li>
<li><a href="#section2">2. Creating Arrays</a></li>
<li><a href="#section3">3. Array Attributes, Indexing &amp; Slicing</a></li>
<li><a href="#section4">4. Vectorized Operations</a></li>
<li><a href="#section5">5. Broadcasting</a></li>
<li><a href="#section6">6. Quick Reference — Cheat Sheet</a></li>
<li><a href="#section7">7. Hands-On Lab — NumPy Array Manipulation</a></li>
<li><a href="#section8">8. Best Practices &amp; Reproducibility</a></li>
<li><a href="#section9">9. Summary — What I Learned Today</a></li>
</ol>
</div>


<a id="section0"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">0. Setup — Importing NumPy</h2>

<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> NumPy is not part of "plain" Python. It is a separate library that we install once (Day 1) and then import at the top of every notebook where we need it. The universal convention in the entire data-science world is to import it with the short nickname <code>np</code>. Every tutorial, every course, every real project does this — so you should too, for consistency.
</div>


In [1]:

import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.4.6


<a id="section1"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">1. Why NumPy Exists — The Big Picture</h2>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">1.1 The problem with plain Python lists</h3>

A normal Python <code>list</code> is very flexible: it can hold mixed types (numbers, strings, anything), and it can grow or shrink. But that flexibility comes at a cost — Python has to check the type of every single element every time it does something with it. When you have millions of numbers (which is completely normal in AI/ML), this becomes painfully slow.

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">1.2 The NumPy solution: the ndarray</h3>

NumPy's core object is called the <b>ndarray</b> ("n-dimensional array"). Think of it as a super-charged list with two big differences:

<ul>
<li><b>Homogeneous</b>: every element must be the <i>same data type</i> (e.g. all integers, or all floats). This is what a spreadsheet column looks like too.</li>
<li><b>Fixed operations run in C, not Python</b>: NumPy is actually written in the C programming language under the hood. So when you tell NumPy "multiply every number in this array by 2", it does that in raw, compiled C code — which can be 10x–100x faster than a Python <code>for</code> loop doing the same thing.</li>
</ul>

<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b> Rule of thumb: if you ever find yourself writing a Python <code>for</code> loop to do math over a list of numbers, stop — there is almost always a faster, more readable NumPy way to do the same thing without a loop. This idea is called <b>vectorization</b>, and it is the single most important habit to build this week.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">1.3 Why this matters for your whole internship</h3>

NumPy isn't just "one more library" — it is the foundation everything else sits on:

<ul>
<li><b>Pandas</b> (tomorrow, Day 4) stores its data internally as NumPy arrays.</li>
<li><b>Scikit-learn</b>, <b>TensorFlow</b>, and <b>PyTorch</b> (later phases) all expect data in NumPy-array-like form, and their internal math is built on the same ideas you'll learn today.</li>
</ul>

<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> This is why Day 3 matters so much: shaky NumPy fundamentals will slow you down in every single week that follows.
</div>


<a id="section2"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">2. Creating Arrays</h2>

<div style="border-left:5px solid #FACC15; background-color:#fffbea; padding:10px 15px; margin:10px 0; border-radius:4px; color:#78350f;">
<b>Goal:</b> Understand every common way to make a NumPy array, and know which one to reach for in which situation.
</div>

There isn't just one way to create an array — different situations call for different creation functions. Let's go through each one slowly.


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">2.1 From a Python list — np.array()</h3>

The most direct way: you already have a Python list of numbers, and you convert it into an ndarray.


In [2]:
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> You can also pass a list-of-lists to create a 2D array (rows and columns) — we will use this a lot below.
</div>

In [7]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print(m)

[[1 2 3]
 [4 5 6]]


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">2.2 Arrays filled with zeros or ones — np.zeros() / np.ones()</h3>

Very often in ML you need a "blank" array to start with — for example, to store results you will fill in later, or to initialize weights. <code>np.zeros()</code> and <code>np.ones()</code> create arrays pre-filled with 0 or 1.

The argument you pass is the <b>shape</b> — for a 2D array, this is a tuple <code>(rows, columns)</code>.


In [6]:
z = np.zeros((2, 3))
print("zeros:\n", z)

o = np.ones(5)
print("ones:\n", o)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [1. 1. 1. 1. 1.]


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">2.3 A range of numbers — np.arange()</h3>

This is the NumPy version of Python's built-in <code>range()</code>, but it returns an actual array (and it also accepts decimal steps, which plain <code>range()</code> cannot do).

Syntax: <code>np.arange(start, stop, step)</code> — note that <code>stop</code> is <b>not included</b> (this is called a "half-open interval", and it matches how Python's <code>range()</code> behaves too).


In [8]:
r = np.arange(0, 10, 2)
print(r)

[0 2 4 6 8]


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">2.4 Evenly spaced values — np.linspace()</h3>

<code>np.linspace(start, stop, n)</code> is different from <code>arange</code>: instead of choosing a *step size*, you choose *how many numbers you want*, and NumPy spaces them evenly between start and stop — and here, <code>stop</code> <b>IS included</b>.


In [ ]:
l = np.linspace(0, 1, 5) 
print(l)

[0.   0.25 0.5  0.75 1.  ]


<div style="border-left:5px solid #BE185D; background-color:#fff0f6; padding:10px 15px; margin:10px 0; border-radius:4px; color:#7a0d3d;">
<b>Important:</b> <code>arange</code> vs <code>linspace</code> is a very common point of confusion. Remember it this way: <b>arange</b> = you control the <i>step</i>; <b>linspace</b> = you control the <i>count</i> of numbers.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">2.5 Random arrays — np.random.rand()</h3>

Useful for testing code, simulations, or initializing values before training a model. <code>np.random.rand(shape)</code> generates random decimal numbers between 0 (inclusive) and 1 (exclusive).


In [ ]:
rnd = np.random.rand(3, 3)
print(rnd)

[[0.73913371 0.90211358 0.70142761]
 [0.88065117 0.56679189 0.93894841]
 [0.0797649  0.00478789 0.18761621]]


<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b> Because these numbers are random, they will be different every time you run the cell. In real projects we usually fix the random seed so results are reproducible — you will see this with <code>np.random.seed(...)</code> below in the Best Practices section.
</div>

<a id="section3"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">3. Array Attributes, Indexing &amp; Slicing</h2>

<div style="border-left:5px solid #FACC15; background-color:#fffbea; padding:10px 15px; margin:10px 0; border-radius:4px; color:#78350f;">
<b>Goal:</b> Be able to read the shape/dtype of any array, and pull out exactly the rows, columns, or single values you need.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">3.1 Attributes — asking the array about itself</h3>

Every NumPy array carries some built-in information about itself, called <b>attributes</b>. You don't call these with parentheses (no <code>()</code>) — you just read them like a property.


In [12]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])

print("shape:", m.shape) 
print("ndim :", m.ndim) 
print("dtype:", m.dtype) 
print("size :", m.size) 

shape: (2, 3)
ndim : 2
dtype: int64
size : 6


<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> <b>shape</b> = the &quot;dimensions&quot; of the array, written as (rows, columns) for 2D. <b>dtype</b> = what kind of number is stored (integer, float, etc.) — remember, ALL elements in one array must share the same dtype. <b>ndim</b> = how many dimensions (1D, 2D, 3D...). <b>size</b> = the total count of numbers in the array.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">3.2 Indexing — getting ONE specific element</h3>

For a 1D array, indexing works exactly like a Python list: <code>a[0]</code> is the first element.

For a 2D array, you use a <b>comma</b> to separate row and column: <code>array[row, column]</code>. This is different from a nested list, where you would need <code>list[row][column]</code> — NumPy lets you do it in a single set of brackets.


In [ ]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])

print(m[0, 2]) 
print(m[1, 0])

3
4


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">3.3 Slicing — getting a RANGE of elements</h3>

A slice uses a colon <code>:</code> to mean "everything" or "a range" along that axis. This is one of the most useful things you will do with NumPy every single day.


In [ ]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])

print("all rows, column 1:      ", m[:, 1])  
print("row 1, all columns:      ", m[1, :])
print("all rows, first 2 cols:  \n", m[:, 0:2])

all rows, column 1:       [2 5]
row 1, all columns:       [4 5 6]
all rows, first 2 cols:  
 [[1 2]
 [4 5]]


<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> Read <code>m[:, 1]</code> out loud as: &quot;give me : (all) rows, and column 1&quot;. Read <code>m[1, :]</code> as: &quot;give me row 1, and : (all) columns&quot;. Once you can read slices out loud like this, they stop being confusing.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">3.4 Boolean Masking — filtering by a CONDITION</h3>

Instead of selecting by position (index 0, index 1...), you can select by a <i>condition</i> — e.g. "give me every value greater than 2". This works in two steps:
<ol>
<li>Write the condition — this creates a new array of <code>True</code>/<code>False</code> values, one for each element (this is called a <b>boolean mask</b>).</li>
<li>Put that mask inside square brackets on the original array — NumPy keeps only the elements where the mask is <code>True</code>.</li>
</ol>


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

mask = a > 3
print("the mask itself:", mask)   

filtered = a[mask]
print("filtered values:", filtered) 


print(a[a > 3])

the mask itself: [False False False  True  True  True]
filtered values: [4 5 6]
[4 5 6]


<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b> Boolean masking is EXACTLY the same idea as Pandas filtering (which you'll learn tomorrow, Day 4) — e.g. <code>df[df[&quot;age&quot;] &gt; 30]</code>. If you understand masking here, Day 4 filtering will feel completely familiar.
</div>

<a id="section4"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">4. Vectorized Operations</h2>

<div style="border-left:5px solid #FACC15; background-color:#fffbea; padding:10px 15px; margin:10px 0; border-radius:4px; color:#78350f;">
<b>Goal:</b> Stop writing loops for math on arrays — let NumPy apply the operation to every element at once.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">4.1 What &quot;vectorized&quot; means</h3>

A vectorized operation applies to an entire array at once, with no explicit <code>for</code> loop written by you. NumPy handles the looping internally, in fast C code.


In [17]:
a = np.array([1, 2, 3, 4])

print(a * 2)        
print(a + a)       
print(a ** 2)     

[2 4 6 8]
[2 4 6 8]
[ 1  4  9 16]


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">4.2 Compare: the SLOW loop way vs the FAST vectorized way</h3>

This side-by-side comparison is the whole point of NumPy — same result, very different code (and very different speed on large data).


In [ ]:
numbers = [1, 2, 3, 4, 5]


doubled_slow = []
for n in numbers:
    doubled_slow.append(n * 2)
print("loop result:      ", doubled_slow)

arr = np.array(numbers)
doubled_fast = arr * 2
print("vectorized result:", doubled_fast)

loop result:       [2, 4, 6, 8, 10]
vectorized result: [ 2  4  6  8 10]


<div style="border-left:5px solid #BE185D; background-color:#fff0f6; padding:10px 15px; margin:10px 0; border-radius:4px; color:#7a0d3d;">
<b>Important:</b> On a small list of 5 numbers you won't notice a speed difference — but on a dataset of 1,000,000 rows (completely normal in real ML work), the vectorized version can be dozens of times faster, and it's also far more readable.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">4.3 Built-in aggregation methods</h3>

NumPy arrays come with handy built-in methods to summarize all their data at once.


In [ ]:
a = np.array([1, 2, 3, 4])

print("mean:", a.mean())  
print("sum :", a.sum())  
print("min :", a.min())  
print("max :", a.max())   
print("std :", a.std())  

mean: 2.5
sum : 10
min : 1
max : 4
std : 1.118033988749895


<a id="section5"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">5. Broadcasting</h2>

<div style="border-left:5px solid #FACC15; background-color:#fffbea; padding:10px 15px; margin:10px 0; border-radius:4px; color:#78350f;">
<b>Goal:</b> Understand the rule that lets NumPy combine arrays of DIFFERENT shapes — and understand why this is exactly what causes most beginner shape-mismatch errors.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">5.1 The simplest case: array + single number</h3>

You've actually already seen broadcasting without naming it — when we did <code>a * 2</code> above. NumPy "stretched" the single number <code>2</code> across every element of the array. That stretching-to-fit behavior is called <b>broadcasting</b>.

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">5.2 The more interesting case: 2D array + 1D array</h3>

NumPy can also add a shorter array to a longer/bigger one, IF the shapes are "compatible". The clearest example: adding one row to every row of a 2D array.


In [ ]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])  

row = np.array([10, 20, 30])     

result = matrix + row
print(result)


[[11 22 33]
 [14 25 36]]


<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> Picture it as NumPy invisibly &quot;copying&quot; the row <code>[10, 20, 30]</code> to match the matrix's 2 rows, WITHOUT actually using extra memory for real copies — that's why it's efficient, not just convenient.
</div>

<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">5.3 The rule for when broadcasting is allowed</h3>

Two shapes are compatible for broadcasting if, comparing their dimensions from the <b>right</b> side:
<ul>
<li>the dimensions are equal, OR</li>
<li>one of the dimensions is 1 (or missing)</li>
</ul>

Our example above: matrix shape <code>(2, 3)</code> vs row shape <code>(3,)</code> → compare from the right: 3 vs 3 match, and the matrix simply has an "extra" dimension (2) that the row doesn't need. So it works.


In [22]:

try:
    bad = np.array([[1, 2, 3], [4, 5, 6]]) + np.array([1, 2]) 
except ValueError as e:
    print("ValueError:", e)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 


<div style="border-left:5px solid #BE185D; background-color:#fff0f6; padding:10px 15px; margin:10px 0; border-radius:4px; color:#7a0d3d;">
<b>Important:</b> This &quot;operands could not be broadcast together&quot; error is one of the most common errors you will see in your entire AI/ML career. Whenever you see it: STOP, print both arrays' <code>.shape</code>, and compare them from the right-hand side using the rule above.
</div>

<a id="section6"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">6. Quick Reference — Cheat Sheet</h2>

<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> Bookmark this section — it summarizes everything above in one glance.
</div>

<table style="width:100%; border-collapse:collapse;">
<tr style="background-color:#38BDF8; color:white;">
<th style="padding:8px; border:1px solid #ccc;">Task</th>
<th style="padding:8px; border:1px solid #ccc;">Code</th>
</tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Create from a list</td><td style="padding:8px; border:1px solid #ccc;"><code>np.array([1,2,3])</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">All zeros / ones</td><td style="padding:8px; border:1px solid #ccc;"><code>np.zeros((r,c))</code> / <code>np.ones(n)</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Range (step-based)</td><td style="padding:8px; border:1px solid #ccc;"><code>np.arange(start, stop, step)</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Range (count-based)</td><td style="padding:8px; border:1px solid #ccc;"><code>np.linspace(start, stop, n)</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Random values</td><td style="padding:8px; border:1px solid #ccc;"><code>np.random.rand(r,c)</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Shape / type / dims</td><td style="padding:8px; border:1px solid #ccc;"><code>arr.shape</code> / <code>arr.dtype</code> / <code>arr.ndim</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Single element</td><td style="padding:8px; border:1px solid #ccc;"><code>arr[row, col]</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Whole row / column</td><td style="padding:8px; border:1px solid #ccc;"><code>arr[1, :]</code> / <code>arr[:, 1]</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Filter by condition</td><td style="padding:8px; border:1px solid #ccc;"><code>arr[arr &gt; 3]</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Math on whole array</td><td style="padding:8px; border:1px solid #ccc;"><code>arr * 2</code>, <code>arr + arr</code></td></tr>
<tr><td style="padding:8px; border:1px solid #ccc;">Summary stats</td><td style="padding:8px; border:1px solid #ccc;"><code>arr.mean()</code>, <code>.sum()</code>, <code>.min()</code>, <code>.max()</code>, <code>.std()</code></td></tr>
</table>


<a id="section7"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">7. Hands-On Lab — NumPy Array Manipulation</h2>

<div style="border-left:5px solid #FACC15; background-color:#fffbea; padding:10px 15px; margin:10px 0; border-radius:4px; color:#78350f;">
<b>Goal:</b> This is the official Day 3 lab from the program. Try to solve each step YOURSELF in the empty cell first, before looking at the solution cell below it.
</div>


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">Step 1 — Create a 2D array of shape (4,4) filled with values 1–16</h3>
<div style="border-left:5px solid #38BDF8; background-color:#eaf6ff; padding:10px 15px; margin:10px 0; border-radius:4px; color:#0c4a6e;">
<b>Note:</b> Hint: <code>np.arange(1, 17)</code> gives you the 16 numbers in one long line — you then need to reshape that line into 4 rows × 4 columns using <code>.reshape(4, 4)</code>.
</div>

In [23]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
print("shape:", arr.shape)
print("dtype:", arr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
shape: (4, 4)
dtype: int64


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">Step 2 — Extract the second column and the last row</h3>

In [ ]:
second_column = arr[:, 1]   
last_row = arr[-1, :]         

print("second column:", second_column)
print("last row     :", last_row)

second column: [ 2  6 10 14]
last row     : [13 14 15 16]


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">Step 3 — Use a boolean mask to select all values greater than the array's mean</h3>

In [24]:
mean_value = arr.mean()
above_mean = arr[arr > mean_value]

print("mean value  :", mean_value)
print("above mean  :", above_mean)

mean value  : 8.5
above mean  : [ 9 10 11 12 13 14 15 16]


<h3 style="color:#FACC15; font-weight:bold; background-color:#1f2933; display:inline-block; padding:4px 10px; border-radius:6px;">Step 4 — Add a 1D row array to every row of a 2D array (broadcasting), and verify manually</h3>

In [ ]:
row_to_add = np.array([100, 200, 300, 400])
result = arr + row_to_add
print(result)


print("manual check of row 0:", arr[0, :] + row_to_add)

[[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]
 [113 214 315 416]]
manual check of row 0: [101 202 303 404]


<a id="section8"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">8. Best Practices &amp; Reproducibility</h2>

<div style="border-left:5px solid #BE185D; background-color:#fff0f6; padding:10px 15px; margin:10px 0; border-radius:4px; color:#7a0d3d;">
<b>Important:</b> The program requires fixing a random seed wherever randomness is used, so your results are repeatable by your mentor. Do this any time you use <code>np.random</code>.
</div>


In [ ]:
np.random.seed(42)    
print(np.random.rand(3)) 



[0.37454012 0.95071431 0.73199394]


<a id="section9"></a>
<h2 style="color:#BE185D; font-weight:bold; margin-top:30px;">9. Summary — What I Learned Today</h2>

<div style="border-left:5px solid #4ADE80; background-color:#eafff2; padding:10px 15px; margin:10px 0; border-radius:4px; color:#065f46;">
<b>Tip:</b> 
<ul>
<li>NumPy exists because plain Python lists are too slow and too flexible for heavy numeric work — the <b>ndarray</b> fixes this by being fast and same-type.</li>
<li>There are several ways to <b>create</b> arrays: from a list, zeros/ones, arange (step-based), linspace (count-based), and random.</li>
<li>Every array has useful <b>attributes</b>: shape, dtype, ndim, size.</li>
<li><b>Indexing</b> gets one element (<code>arr[row, col]</code>); <b>slicing</b> gets a range (<code>arr[:, 1]</code>).</li>
<li><b>Boolean masking</b> filters an array by a condition (<code>arr[arr &gt; 3]</code>) — this is the same idea we'll reuse in Pandas tomorrow.</li>
<li><b>Vectorized operations</b> apply math to a whole array at once, replacing slow Python loops.</li>
<li><b>Broadcasting</b> lets NumPy combine differently-shaped arrays IF their shapes are compatible from the right — this is also the #1 source of shape-mismatch errors, so always check <code>.shape</code> when something breaks.</li>
</ul>

</div>

